[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8", "wheel"]

[project]
name = "package_statistics"
dynamic = ["version"]
description = ""
dependencies = []
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "ruff",
    "tox",
]

[project.scripts]
package_statistics = "package_statistics:main"

[tool.setuptools_scm]

[tool.ruff]
src = ["src", "tests"]
ignore = [
]
line-length = 79
select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "PL",   # Pylint
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    env_list =
        py{38,39,310,311} 
        lint

    [testenv]  # settings common to all environments 
    commands = 
        python -m unittest discover tests/ "test_*.py"

    [testenv:lint]
        allowlist_externals = ruff
    commands = 
        ruff .
"""
