[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "package_statistics"
version = "0.0.0"
description = ""
dependencies = []
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "black",
    "tox",
]

[project.scripts]
package_statistics = "package_statistics:main"

[tool.tox]
legacy_tox_ini = """
    [tox]
    env_list =
        py{38,39,310,311} 
        lint

    [testenv]  # settings common to all environments 
    commands = 
        python -c "print('Test placeholder')"

    [testenv:lint]
    commands = 
        python -c "raise ValueError()"  # Force fail
"""
