name: Code CI

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4  # version of the action
        with:
          python-version: '3.11'
      - name: Install module
        run: pip install .[dev]
      - name: Linting
        run: tox -e lint
      - name: Typing
        run: tox -e type

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install package
        run: pip install .[dev]
      - name: Execute test runner
        run: tox -e py
      - name: Produce the coverage report
        if: ${{ matrix.python==3.10 }}
        run: | 
          tox -e report
      - name: Store the coverage report
        if: ${{ matrix.python==3.10 }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: pip install coverage
      - name: Fetch the coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - run: coverage report --data-file=./.coverage --fail-under=100 --skip-empty